// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SaLes__APIs.EntityLayer;

public partial class MediaDataObject
{
    public Guid Oid { get; set; }

    public byte[] MediaData { get; set; }

    public string MediaDataKey { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? GCRecord { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}