// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SaLes__APIs.EntityLayer;

public partial class SelasContext : DbContext
{
    public SelasContext(DbContextOptions<SelasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<Invoice> Invoice { get; set; }

    public virtual DbSet<MediaDataObject> MediaDataObject { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<RowInvoice> RowInvoice { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomId);

            entity.ToTable("Customer");

            entity.HasIndex(e => e.GCRecord, "iGCRecord_Customer");

            entity.Property(e => e.CustomId).ValueGeneratedNever();
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PhoneNumber).HasMaxLength(100);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("Invoice");

            entity.HasIndex(e => e.Customer, "iCustomer_Invoice");

            entity.HasIndex(e => e.GCRecord, "iGCRecord_Invoice");

            entity.Property(e => e.Oid).ValueGeneratedNever();
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.ResDeletion).HasMaxLength(100);

            entity.HasOne(d => d.CustomerNavigation).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.Customer)
                .HasConstraintName("FK_Invoice_Customer");
        });

        modelBuilder.Entity<MediaDataObject>(entity =>
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("MediaDataObject");

            entity.HasIndex(e => e.GCRecord, "iGCRecord_MediaDataObject");

            entity.Property(e => e.Oid).ValueGeneratedNever();
            entity.Property(e => e.MediaDataKey).HasMaxLength(100);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("Product");

            entity.HasIndex(e => e.GCRecord, "iGCRecord_Product");

            entity.HasIndex(e => e.Image, "iImage_Product");

            entity.HasIndex(e => e.RowInvoice, "iRowInvoice_Product");

            entity.Property(e => e.Oid).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(100);

            entity.HasOne(d => d.ImageNavigation).WithMany(p => p.Products)
                .HasForeignKey(d => d.Image)
                .HasConstraintName("FK_Product_Image");

            entity.HasOne(d => d.RowInvoiceNavigation).WithMany(p => p.Products)
                .HasForeignKey(d => d.RowInvoice)
                .HasConstraintName("FK_Product_RowInvoice");
        });

        modelBuilder.Entity<RowInvoice>(entity =>
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("RowInvoice");

            entity.HasIndex(e => e.GCRecord, "iGCRecord_RowInvoice");

            entity.HasIndex(e => e.Invoice, "iInvoice_RowInvoice");

            entity.HasIndex(e => e.Product, "iProduct_RowInvoice");

            entity.Property(e => e.Oid).ValueGeneratedNever();

            entity.HasOne(d => d.InvoiceNavigation).WithMany(p => p.RowInvoices)
                .HasForeignKey(d => d.Invoice)
                .HasConstraintName("FK_RowInvoice_Invoice");

            entity.HasOne(d => d.ProductNavigation).WithMany(p => p.RowInvoices)
                .HasForeignKey(d => d.Product)
                .HasConstraintName("FK_RowInvoice_Product");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}